Add missing override specifiers
Build failed on Android when using clang.

error: '<name>' overrides a member function but is not marked 'override'
      [-Werror,-Winconsistent-missing-override]

Change-Id: I080f8145b5a1c12bacf99f9c08f9e78271e5837a
Reviewed-by: Frederik Gladhorn <frederik.gladhorn@qt.io>