Fix change-of-sign warning in the new QML compiler
The m_line and m_column members are of type quint16, so -1 is not
valid. BTW, aren't 65535 possible lines too few?

qqmlboundsignal.cpp(92): error #68: integer conversion resulted in a change of sign

Change-Id: I2f73c276c5fc9b6988b5fa4274f7fa3f6bb85c4b
Reviewed-by: Simon Hausmann <simon.hausmann@digia.com>