Fix Unity build of QtQml
Move the logging categories out of the namespaces, fixing errors
like:

qtdeclarative/src/qmlls/qqmlformatting.cpp: In function 'const QLoggingCategory& formatLog()':
qtdeclarative/src/qmlls/qqmlformatting.cpp:14:13: error: reference to 'QtPrivateLogging' is ambiguous
In file included qt-dev/qt-dev/qtdeclarative/src/qmldom/qqmldomitem_p.h:24,
                 qt-dev/build-qt-dev/qtdeclarative/include/QtQmlDom/6.9.0/QtQmlDom/private/qqmldomitem_p.h:1,
                 qt-dev/build-qt-dev/qtdeclarative/src/qmlls/QmlLSPrivate_autogen/EWIEGA46WW/../../../../../../../../..qtdeclarative/src/qmlls/qqmlcodemodel_p.h:25,
                 qt-dev/build-qt-dev/qtdeclarative/src/qmlls/QmlLSPrivate_autogen/EWIEGA46WW/moc_qqmlcodemodel_p.cpp:9,
                 qt-dev/build-qt-dev/qtdeclarative/src/qmlls/QmlLSPrivate_autogen/mocs_compilation.cpp:3,
                 qt-dev/build-qt-dev/qtdeclarative/src/qmlls/CMakeFiles/QmlLSPrivate.dir/Unity/unity_0_cxx.cxx:4:
qt-dev/qt-dev/qtdeclarative/src/qmldom/qqmldomerrormessage_p.h:35:11: note: candidates are: 'namespace QQmlJS::Dom::QtPrivateLogging { }'
In file included qt-dev/install-qt-dev/include/QtLanguageServer/6.9.0/QtLanguageServer/private/qlanguageservergen_p.h:22,
                 qt-dev/install-qt-dev/include/QtLanguageServer/6.9.0/QtLanguageServer/private/qlanguageserverprotocol_p.h:19,
                 qt-dev/build-qt-dev/qtdeclarative/src/qmlls/QmlLSPrivate_autogen

Task-number: QTBUG-115140
Change-Id: Ia21dce6cc37e8b8a9cced6cb6e267125dba0df9f
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>
(cherry picked from commit 15ae3f532b1328c377d9775fbf75dc2647cc016b)