QQmlPropertyCache: Fix developer build with MinGW.
Reorder inline functions so that QQmlPropertyCache::ensureResolved()
is visible from where it is invoked (QQmlPropertyCache::property()),
fixing error:

qtdeclarative/src/qml/qml/qqmlpropertycache_p.h:559:26: error: 'QQmlPropertyData* QQmlPropertyCache::ensureResolved(QQmlPropertyData*) const' redeclared without dllimport attribute after being referenced with dll linkage [-Werror]
 inline QQmlPropertyData *QQmlPropertyCache::ensureResolved(QQmlPropertyData *p) const

Change-Id: Id0f0b5b92d377c71f5950011ba993e53d783bfb8
Reviewed-by: Erik Verbruggen <erik.verbruggen@theqtcompany.com>