Fix false-positive GCC 13 warnings about possible dangling pointers
They aren't dangling because in both cases the iterator is pointing to
an element in the hash, which isn't getting destroyed in that
expression.

quicklintplugin.cpp:60:25: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
quicklintplugin.cpp:60:67: note: the temporary was destroyed at the end of the full expression ‘bindings.QQmlSA::Binding::Bindings::constBegin().QMultiHash<QString, QQmlSA::Binding>::const_iterator::value()’

Change-Id: I9201d9ecf52f4146bb04fffd176446ad02755f02
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>