Remove unused variables in src/quick
Clang 15 started to give me -Wunused-but-set-variable on Ubuntu. I
suspect this is due to my local update (which could have included the
compiler as well). The following pattern (rightly) detected as "unused":

int foo = 0; // declaration
// ...
++foo; // usage, but in fact, this is just "an update of a definition"
// ... - foo is never used in any other expression, so warn

Specific messages:

qtdeclarative/src/quick/items/qquickwindow.cpp:2036:13: error: variable 'removed' set but not used [-Werror,-Wunused-but-set-variable]
        int removed = 0;
            ^
qtdeclarative/src/quick/items/qquickwindow.cpp:2035:13: error: variable 'added' set but not used [-Werror,-Wunused-but-set-variable]
        int added = 0;
            ^
qtdeclarative/src/quick/items/qquickwindow.cpp:2037:13: error: variable 'replaced' set but not used [-Werror,-Wunused-but-set-variable]
        int replaced = 0;
            ^

qtdeclarative/src/quick/scenegraph/qsgdistancefieldglyphnode.cpp:324:9: error: variable 'subnodeCount' set but not used [-Werror,-Wunused-but-set-variable]
    int subnodeCount = 0;
        ^

Pick-to: 6.3 6.2
Change-Id: I2a4d294a2527cee98f4e882050dc160efd04501e
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
Reviewed-by: Shawn Rutledge <shawn.rutledge@qt.io>