Silence another GCC 8 warning in qpodvector
qtdeclarative/src/qml/qml/ftw/qpodvector_p.h:119:22: error: ‘void* memmove(void*, const void*, size_t)’ writing to an object of non-trivially copyable type ‘class QQuickBasePositioner::PositionedItem’; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
             ::memmove(m_data + idx, m_data + idx + count,

Change-Id: I049703a0a6bb4432dfd3d3ce3c8cef13e9c2e31a
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>
(cherry picked from commit 55f71cdfc5746a71bcb89f0fa4ff3447cb8b5514)
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>