Fix broken -no-qml-debug
4975a33ba9aa357ba2bca93e292b1fbcfb34c24e introduced QQmlDebugTranslationService.
If -no-qml-debug is provided the dummy class misses "public:".

qml/qqmlbinding.cpp:401:54: error: 'virtual void QQmlDebugTranslationService::foundTranslationBinding(QQmlTranslationBinding*, QObject*, QQmlContextData*)' is private within this context

Change-Id: I0f4ebd4d935a17aa7a679d2d87d98d03b0e1fcbb
Reviewed-by: Tim Jenssen <tim.jenssen@qt.io>