Doc: Fix compilation errors in snippet
error: Non-const static data member must be initialized out of line

Change-Id: I2b2785529ac8fd0d81e49c226065d263df417e17
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
(cherry picked from commit 37730c6e1786e49083263c4deff5c37db7595cd1)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>