QQuickListView: suppress GCC13 warning about maybe-uninitialized pos
It is initialized in all possible branches, except in case the
switch (headerPositioning) didn't match anything. We could fix that by
making that switch an IILE, but it doesn't cost us much to simply
initialize pos.

In function ‘constexpr const T& qMin(const T&, const T&) [with T = double]’,
    inlined from ‘constexpr const T& qBound(const T&, const T&, const T&) [with T = double]’
    inlined from ‘virtual void QQuickListViewPrivate::fixup(QQuickFlickablePrivate::AxisData&, qreal, qreal)’
qminmax.h:40:73: error: ‘pos’ may be used uninitialized [-Werror=maybe-uninitialized]
qquicklistview.cpp:1690:15: note: ‘pos’ was declared here

Change-Id: Ide4dbd0777a44ed0870efffd1739193e2c1df40c
Reviewed-by: Oliver Eftevaag <oliver.eftevaag@qt.io>
(cherry picked from commit 8f895ea26d5d524677dd5b63f43bdd7e81339840)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>