Silence GCC 8 warnings in qpodvector
qpodvector_p.h:90:34: error: ‘void* realloc(void*, size_t)’ moving an object of non-trivially copyable type ‘class QQuickBasePositioner::PositionedItem’; use ‘new’ and ‘delete’ instead [-Werror=class-memaccess]
             m_data = (T *)realloc(m_data, m_capacity * sizeof(T));

qpodvector_p.h:94:22: error: ‘void* memmove(void*, const void*, size_t)’ writing to an object of non-trivially copyable type ‘class QQuickBasePositioner::PositionedItem’; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
             ::memmove(m_data + idx + 1, m_data + idx, moveCount * sizeof(T));

Change-Id: I37088986a0f8613152a355ed6f3f9572316fa607
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>
(cherry picked from commit 622decbe3b2478496295e57d59f9cf16a9f70a13)
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>