Fix build without opengl
The default backend code still depends on OpenGL:
qquickrendercontrol.cpp: undefined reference to `QSGDefaultRenderContext::staticMetaObject'

Change-Id: I7857f28f6ce8997dd38119c1d367d8cdbb3cbf37
Reviewed-by: Laszlo Agocs <laszlo.agocs@qt.io>