QtQml: Fix unity build
Disambiguate "Default", fixing:
QQmlSA::GenericPass::resolveIdToElement(QAnyStringView, const QQmlSA::Element&)’:
src/qmlcompiler/qqmlsa.cpp:1398:57: error: reference to ‘Default’ is ambiguous
           id.toString(), QQmlJSScope::scope(context), Default, result);
candidates are: QmlJS::PrecedenceValues QQmlJS::Default
                QQmlJSScopesByIdOption::Default

Task-number: QTBUG-115140
Change-Id: I16735af05aa62e934f8b68c27c10164b5659250d
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>
(cherry picked from commit a2dad84d96266bc30b63fd11f16093ab82289b35)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>