QSGGeometry: add Q_DISABLE_COPY_MOVE
This is a polymorphic class, so that already tells us this should never
be copied. Moreover, it has a reference member, so the default
assignment operator cannot be instantiated.

error: use of deleted function ‘QSGGeometry& QSGGeometry::operator=(const QSGGeometry&)’
qsggeometry.h:51:22: note: ‘QSGGeometry& QSGGeometry::operator=(const QSGGeometry&)’ is implicitly deleted because the default definition would be ill-formed:
qsggeometry.h:51:22: error: non-static reference member ‘const QSGGeometry::AttributeSet& QSGGeometry::m_attributes’, cannot use default assignment operator

Found while compiling PyQt, which is obviously wrong, but this should
improve the error message output.

Pick-to: 5.15 6.2 6.4
Change-Id: I07ec23f3cb174fb197c3fffd1721f614929a18f4
Reviewed-by: Laszlo Agocs <laszlo.agocs@qt.io>