Add missing QPainterPath includes
.../qsgadaptationlayer_p.h(500): error C2079:
'QSGDistanceFieldGlyphCache::GlyphData::path' uses undefined
class 'QPainterPath'

.../splineeditor.cpp(168): error C2079: 'path' uses undefined
class 'QPainterPath'

Change-Id: I5f905aa31b24f71c65889047065ab43725fb6733
Reviewed-by: Andy Shaw <andy.shaw@qt.io>