QQuickWindow: Change 0 to nullptr for removeAll
The change in qtbase which made removeAll had the unfortunate side
effect that were deducing type int now (instead of converting 0 to the
null pointer constant), which -after a few indirections- leads to
 3365: src/quick/items/qquickwindow.cpp:3785:22:   required from here
 /usr/include/c++/10/bits/predefined_ops.h:268:17: error: ↩
 ISO C++ forbids comparison between pointer and integer [-fpermissive]
   268 |  { return *__it == _M_value; }
       |           ~~~~~~^~~~~~~~~~~

Change-Id: I2ba7c561a2431a8a71f77068daef60d5ae62f17c
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>