QV4Object: fix GCC 6.1 tautologial compare warning
GCC warned:

  qtdeclarative/src/imports/localstorage/plugin.cpp:152:126: error: self-comparison always evaluates to true [-Werror=tautological-compare]

Fix by comparing the types for equality instead of the addresses of
their static_vtbls.

Task-number: QTBUG-53373
Change-Id: Idd1598610ad6381c03c3a46abe56a332726bd6a0
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
Reviewed-by: Shawn Rutledge <shawn.rutledge@qt.io>