Doc: fix warning in ItemDelegate snippet
The error was:

TypeError: Cannot read property 'width' of null

Change-Id: I0505e806130769fb7a2ed77b18c80393476edafd
Reviewed-by: Richard Moe Gustavsen <richard.gustavsen@qt.io>
(cherry picked from commit 7e3e1295f4e240afc9532bc0ab47ff3644ffc008)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 4397d6490ad96be31b85af6acbc911c19d7682b9)
(cherry picked from commit e3cc449dfc88a7a070df33b1a20b368e54b55775)