Fix errors and warning if -no-feature-quick-viewtransitions is used
src/quick/items/qquickitemview.cpp:2657:22: error:
no member named 'transitionableItem' in 'FxViewItem'
 2657 |         delete item->transitionableItem;
      |                ~~~~  ^

src/quick/items/qquickitemview.cpp:2658:15: error:
no member named 'transitionableItem' in 'FxViewItem'
 2658 |         item->transitionableItem = nullptr;
      |         ~~~~  ^

src/quick/items/qquicklistview.cpp:3746:166: warning:
unused parameter 'movingIntoView' [-Wunused-parameter]
 3746 | bool [...]:applyInsertionChange([...] *movingIntoView)
      |                                        ^

Change-Id: Ia37a0991ec5a75b0c52595daf88ccbcf94daa0aa
Reviewed-by: Mitch Curtis <mitch.curtis@qt.io>
(cherry picked from commit ffb039e8faa880cb06439d152d6f8772d91bf495)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 812d88dd71d9ab4d7d5cfeb90aff2828780a3fbd)