Fix long file name generated for certain qmlcache.qrc
When compiling qtvirtualkeyboard with MSVC, it may choke on the long
file name generated for certain *_qmlcache.qrc files. Specifically,
these files are originally generated by qmake, therefore reside in the
build directory.

For example, this happens when compiling qtvirtualkeyboard out-of-tree
using shadow build (e.g. in Qt Creator):

qrc____build_qtvirtualkeyboard_Desktop_Qt_5_12_0_MSVC2017_x86_64_Debug_src_virtualkeyboard_.rcc_release_qmake_virtualkeyboard_layouts_qmlcache.cpp
c1xx: fatal error C1083: Cannot open source file: '.rcc\release\qrc____build_qtvirtualkeyboard_Desktop_Qt_5_12_0_MSVC2017_x86_64_Debug_src_virtualkeyboard_.rcc_release_qmake_virtualkeyboard_layouts_qmlcache.cpp': No such file or directory

This change changes the base directory to $$OUT_PWD for paths which
point outside the source directory.

Change-Id: I9733af98d916a60ca1ab02cd49ab67024f1db086
Reviewed-by: Jarkko Koivikko <jarkko.koivikko@code-q.fi>
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@qt.io>