DOM: fix use of dangling reference
Found by GCC 16:
qqmldommoduleindex.cpp:263:26: error: dangling pointer to an unnamed temporary may be used [-Werror=dangling-pointer=]
  263 |                     vNow = versionPtr->minorVersion;
      |                     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
qqmldommoduleindex.cpp:245:57: note: unnamed temporary defined here
  245 |             Version const *versionPtr = exportItem.field(Fields::version).as<Version>();
      |                                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

GCC is correct: DomItem::field returns a new DomItem by value, which
creates a new ElementT (a std::variant). It's a pointer into that object
that DomItem::as() → SimpleObjectWrapBase::as() returns.

Amends commit 52d61e705ee606f3b673c757bdf253bdf6134a3b from 6.2.

Pick-to: 6.8
Change-Id: If68159d8b150042733effffd6b6955993f3a74d7
Reviewed-by: Semih Yavuz <semih.yavuz@qt.io>
(cherry picked from commit debbdc9a5d2e59ac52f70aaf11267a4d74612672)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit d9c40aba5d30869e43da2b40d913926430d361a1)