Silence a GCC 8 warning in qquickanimation
qtdeclarative/src/quick/util/qquickanimation.cpp:1669:109: error: cast between incompatible function types from ‘QVariant (*)(qreal&, qreal&, qreal)’ {aka ‘QVariant (*)(double&, double&, double)’} to ‘QVariantAnimation::Interpolator’ {aka ‘QVariant (*)(const void*, const void*, double)’} [-Werror=cast-function-type]
         d->interpolator = reinterpret_cast<QVariantAnimation::Interpolator>(&_q_interpolateClockwiseRotation);

Change-Id: I8da70ef666deb3cbdbf05c5bac89f705a2ec5ea8
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>
(cherry picked from commit 12afec6c2f89264b7344f9221763898c77a396fc)
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>