Fix Clang 10 warning about converting ULLONG_MAX to double
The compiler must convert ULLONG_MAX to double before adding 1, so this
expression was wrong.

 MathExtras.h:402:43: error: implicit conversion from 'unsigned long long' to 'double' changes value from
 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-int-float-conversion]

Task-number: QTBUG-83666
Change-Id: I99ab0f318b1c43b89888fffd160b4a95a258423b
Reviewed-by: Lars Knoll <lars.knoll@qt.io>
(cherry picked from commit 1250d8b5b95eecac767a23563717e53faa5d3b8a)
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>