Fix tons of reference errors in tst_qquickpositioners
Due to missing context properties:
ReferenceError: fooBar is not defined

Task-number: QTBUG-33018
Change-Id: Ibba95ab688a8d5cadc94bdeb30d0ec087ffe3c0c
Reviewed-by: Alan Alpert <aalpert@blackberry.com>