Fix static builds on Windows
Fixes issues like

  qml_qmltyperegistrations.cpp(28): error C2375: 'qml_register_types_QtQml': redefinition; different linkage
  qtbase\include\QtQml\6.2.0\QtQml\private\../../../../../../../src/qtdeclarative/src/qml/qtqmlglobal_p.h(62): note: see declaration of 'qml_register_types_QtQml'

Change-Id: I063b60638978faa4e79cbf7eb75849a367730893
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>
(cherry picked from commit d0cb449208ff618498e3e129b4af1b22086da082)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>