controlstestutils_p.h: add missing QTest include
I couldn't reproduce it locally, but the error on CI was:

[...]/qtesthelpers_p.h(110): error C2653: 'QTest': is not a class or namespace name
[...]/qtesthelpers_p.h(110): error C3861: 'qWaitFor': identifier not found

https://codereview.qt-project.org/c/qt/qtdeclarative/+/716225/8#message-7534c492b7381bcd70a60739d59a033e4c91d1cb

This is necessary for the follow-up patch that uses
ensurePositionTopLeft in TRY_VERIFY_POPUP_OPENED.

Pick-to: 6.11 6.12
Change-Id: Ifc613ad58ee32e9b7d21cdc19885ce912c8d78f5
Reviewed-by: SanthoshKumar Selvaraj <santhosh.kumar.selvaraj@qt.io>