Fix build with -no-feature-menu
.../qwidgetplatformsystemtrayicon.cpp.o: in function
`QWidgetPlatformSystemTrayIcon::createMenu() const':
qwidgetplatformsystemtrayicon.cpp:(.text+0xe5): undefined reference to
`QWidgetPlatformMenu::QWidgetPlatformMenu(QObject*)'

Change-Id: I7f953848860b71dcdd2ef18e14e414ca42ecc42b
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit edd5499c60f9b5d085c8f99a852a00251a1e995c)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>