Fix warning by ICC: function without return value
Yes, it can't be reached due to the Q_UNREACHABLE(). ICC expands that to an
__assume(0), which I guess isn't strong enough.

qv4isel_util_p.h(94): error #1011: missing return statement at end of non-void function "QQmlJS::convertToValue"

Change-Id: I41d9fd7382a41fe0e753812fc1d71fdc802ef854
Reviewed-by: Lars Knoll <lars.knoll@digia.com>