qmltooling: don't assert(this)
`Q_ASSERT(this)` was added to silence some static analyser warnings for
older clang versions. However this breaks compilation with recent clang
and -Werror:

```
error: 'this' pointer cannot be null in well-defined C++ code; pointer
may be assumed to always convert to true
[-Werror,-Wundefined-bool-conversion]
```

Pick-to: 6.12
Change-Id: I99ecd674bc1238c979ab6428a123b8d3542386b1
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>