Fix ICC warning about change of sign
qv4typedarray.cpp(87): error #68: integer conversion resulted in a change of sign

Change-Id: Iee8cbc07c4434ce9b560ffff13cf917dd8f9012e
Reviewed-by: Simon Hausmann <simon.hausmann@theqtcompany.com>