Remove unused member variable QQmlDebugServerThread::m_block.
Fix CLANG build error:

qqmldebugserver.cpp:115:10: error: private field 'm_block' is not used
      [-Werror,-Wunused-private-field]
    bool m_block;

Change-Id: I3be87c1ec0347b46e90e40c8769aeb507cf22c26
Reviewed-by: Ulf Hermann <ulf.hermann@theqtcompany.com>