Fix build with -no-feature-validator
By removing property, getter, setter and notify signal for validator.

.../qmetatype.h: In instantiation of ‘constexpr bool
QtPrivate::checkTypeIsSuitableForMetaType() [with X = QValidator*]’:
.../qmetatype.h:2589:9:   required from ‘constexpr const
QtPrivate::QMetaTypeInterface* QtPrivate::qTryMetaTypeInterfaceForType()
[with Unique = void; TypeCompletePair =
QtPrivate::TypeAndForceComplete<QValidator*,
std::integral_constant<bool, true> >]’
.../qmetatype.h:2639:102:   required from ‘constexpr const
QtPrivate::QMetaTypeInterface* const qt_metaTypeArray [72]<int,
QVariant, QQmlInstanceModel*, bool, int, int, QString, QString, QString,
QQmlComponent*, QQuickItem*, QQuickPopup*, bool, bool, bool, QString,
QValidator*, QFlags<Qt::InputMethodHint>, bool, bool, double, double,
QVariant, QString, bool, QQuickComboBox::ImplicitContentWidthPolicy,
QQuickComboBox, void, int, void, int, void, void, void, void, void,
void, void, void, void, void, void, void, void, void, void, void, void,
void, void, void, void, void, void, void, void, void, void, void, void,
void, QString, int, int, const QString&, QFlags<Qt::MatchFlag>, int,
const QString&, QVariant, int, int, const QVariant&>’
.../moc_qquickcombobox_p.cpp:588:5:   required from here
.../qmetatype.h:1181:55: error: static assertion failed: Pointer Meta
Types must either point to fully-defined types or be declared with
Q_DECLARE_OPAQUE_POINTER(T *)

Pick-to: 6.5
Change-Id: I0ee5ae9c84bc977571f39788299f1d84a7e582c5
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>