Fix compilation with the Intel compiler
The template function isn't necessary anymore. It actually breaks
the build...

 ARM64Assembler.h(3275): error: no instance of function template "assertUnused" matches the argument list
            argument types are: (bool)
 Assertions.h(238): note: this candidate was rejected because arguments do not match

Change-Id: I27b55fdf514247549455fffd14b1c6dfe92f2b88
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>