qmlls: Fix build with MSVC and latest qtbase
Fixes a deprecation warning:

    qtbase/src/corelib/text/qstringbuilder.h(400): error C2220: the following warning is treated as an error
    qtbase/src/corelib/text/qstringbuilder.h(400): warning C4996: 'QConcatenable<const char [4]>::appendTo': Use fromUtf8, QStringLiteral, or QLatin1StringView

While at it, also change append() to operator+() for
easier readability, and use Latin1 / _L1 for minimal space usage.

Change-Id: I2035b1776aa43b67031f3f6e45460a5966d68f18
Reviewed-by: Jøger Hansegård <joger.hansegard@qt.io>
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
(cherry picked from commit d14bf9803e5bb0d736dd272c3abc9f460422ef40)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>