QSGRhiShaderEffectNode: remove unused m_rc member
Found by Clang after includemocs:

    qsgrhishadereffectnode_p.h:145:30: error: private field 'm_rc' is not used [-Werror,-Wunused-private-field]
        QSGDefaultRenderContext *m_rc;
                                 ^

Pick-to: 6.3 6.2 5.15
Change-Id: I915751abb01d9ff5d57c364be333ca2c171eaa97
Reviewed-by: Mårten Nordheim <marten.nordheim@qt.io>