Doc: fix warning in ItemDelegate snippet
The error was:

TypeError: Cannot read property 'width' of null

Pick-to: 6.7 6.5
Change-Id: I0505e806130769fb7a2ed77b18c80393476edafd
Reviewed-by: Richard Moe Gustavsen <richard.gustavsen@qt.io>
(cherry picked from commit 7e3e1295f4e240afc9532bc0ab47ff3644ffc008)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>