Export QQuickWindowAttached
fd1612d9 broke the qqc2 build:

    error: undefined reference to 'QQuickWindowAttached::staticMetaObject'

Change-Id: Ia52f0e124fa81fecdee0ed006837a93636aa9622
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>