QQmlDiffer: include what you need: <vector>, <algorithm>
I actually got a compile error from Clang 21 here:

  qqmldiffer.cpp:225:5: error: no template named 'vector' in namespace 'std'; did you mean 'QVector'?
    225 |     std::vector<qsizetype> forwardV(2 * D + 1);
        |     ^~~~~~~~~~~
        |     QVector
  qcontainerfwd.h:40:22: note: 'QVector' declared here
     40 | template<typename T> using QVector = QList<T>;
        |                      ^

Include <vector> for std::vector and <algorithm> for std::mismatch().

Amends addc779a9492eea347e3652a1b10c21dc4fdcb87.

Change-Id: Id41da5dc9c03d43867ebb11693aac77c8e35628c
Reviewed-by: Semih Yavuz <semih.yavuz@qt.io>
(cherry picked from commit a32891c3dc01175251087ae78c15647ab58e448b)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>