QQmlListCompositor: suppress GCC 12 -Warray-bounds warnings
Despite my best efforts in teaching GCC 12 to understand that
groupCount is always <= MaxGroupCount, it continued to issue these
warnings:

  In member function ‘void QQmlListCompositor::iterator::incrementIndexes(int, uint)’,
      inlined from ‘void QQmlListCompositor::iterator::incrementIndexes(int)’ at qtdeclarative/src/qmlmodels/qqmllistcompositor_p.h:138:65,
      inlined from ‘void QQmlListCompositor::move(Group, int, Group, int, int, Group, QVector<Remove>*, QVector<Insert>*)’ at qtdeclarative/src/qmlmodels/qqmllistcompositor.cpp:852:40:
  qtdeclarative/src/qmlmodels/qqmllistcompositor_p.h:336:20: error: array subscript 28 is above array bounds of ‘int [11]’ [-Werror=array-bounds]
    336 |             index[i] += difference;
        |             ~~~~~~~^
  qtdeclarative/src/qmlmodels/qqmllistcompositor_p.h: In member function ‘void QQmlListCompositor::move(Group, int, Group, int, int, Group, QVector<Remove>*, QVector<Insert>*)’:
  qtdeclarative/src/qmlmodels/qqmllistcompositor_p.h:154:13: note: while referencing ‘QQmlListCompositor::iterator::index’
    154 |         int index[MaximumGroupCount] = { 0 };
        |             ^~~~~
  In member function ‘void QQmlListCompositor::iterator::incrementIndexes(int, uint)’,
      inlined from ‘void QQmlListCompositor::iterator::incrementIndexes(int)’ at qtdeclarative/src/qmlmodels/qqmllistcompositor_p.h:138:65,
      inlined from ‘void QQmlListCompositor::move(Group, int, Group, int, int, Group, QVector<Remove>*, QVector<Insert>*)’ at qtdeclarative/src/qmlmodels/qqmllistcompositor.cpp:852:40:
  qtdeclarative/src/qmlmodels/qqmllistcompositor_p.h:336:20: error: array subscript 28 is above array bounds of ‘int [11]’ [-Werror=array-bounds]
    336 |             index[i] += difference;
        |             ~~~~~~~^
  qtdeclarative/src/qmlmodels/qqmllistcompositor_p.h: In member function ‘void QQmlListCompositor::move(Group, int, Group, int, int, Group, QVector<Remove>*, QVector<Insert>*)’:
  qtdeclarative/src/qmlmodels/qqmllistcompositor_p.h:154:13: note: while referencing ‘QQmlListCompositor::iterator::index’
    154 |         int index[MaximumGroupCount] = { 0 };
        |             ^~~~~
  cc1plus: all warnings being treated as errors

Therefore, I see no other solution than to suppress the warning the
hard way.

Fixes: QTBUG-103924
Change-Id: Ic46009daa35357c6e6bb0fd1c16d020e360b7525
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
(cherry picked from commit 80f0bf64e49f07a73712998ddc8a0eebd1b660b6)
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>