Fix warnings in QtQml due to ?: with enums of different types
The compiler was complaining a lot about:
qml/parser/qqmljskeywords_p.h:400:57: error: enumeral mismatch in conditional expression: 'QQmlJS::Lexer::<anonymous enum>' vs 'QQmlJSGrammar::VariousConstants' [-Werror=enum-compare]

Change-Id: Ib6acd3fbae048c33626321bf5e7ee8b50bb6b48e
Reviewed-by: Alan Alpert <aalpert@rim.com>