Fix warning in RangeSlider::test_touchDragThreshold test
The warnings were:

TypeError: Cannot assign to read-only property "first"
TypeError: Cannot assign to read-only property "second"

Change-Id: Ida6b0e4491f9ef867454b32c0ce1c4cd33dd841f
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
(cherry picked from commit 87b512cdf417e3e2898bbd5b808b5b837f93b7d5)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>