QQmlListCompositor: fix QT_QML_TRACE_LISTCOMPOSITOR build error
The error was:

[...]/qqmllistcompositor.cpp: In member function ‘void QQmlListCompositor::clear()’:
[...]/qqmllistcompositor.cpp:907:33: error: expected ‘;’ before string constant
  907 |     QT_QML_TRACE_LISTCOMPOSITOR("")
      |                                 ^~
[...]/qqmllistcompositor.cpp:195:103: note: in definition of macro ‘QT_QML_TRACE_LISTCOMPOSITOR’
  195 | #define QT_QML_TRACE_LISTCOMPOSITOR(args) qDebug() << m_end.index[1] << m_end.index[0] << Q_FUNC_INFO args;
      |                                                                                                       ^~~~

Change-Id: I60b16707a31c40c44affe9129bc10bf8c9c393b6
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
(cherry picked from commit 88e588b6bfe5a3daad619705521b4c9329114288)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>