Remove use of anonymous struct in header file
Although all compilers seem to support this, anonymous structs have only
been added formally to C++ 11. Also, this breaks with a change that adds
a constructor to QElapsedTimer:

error: member 'QElapsedTimer QQmlInstantiationInterrupt::<anonymous struct>::timer' with constructor not allowed in anonymous aggregate
        QElapsedTimer timer;
	              ^

Change-Id: I5672060e3a623a5d9c4eb1d4e2981c67b96a1192
Reviewed-by: Simon Hausmann <simon.hausmann@digia.com>