QQuickPageIndicatorPrivate: add missing override
Somehow this passed the 5.9 CI, but the dev branch throws an error:

    qquickpageindicator.cpp:110:10: error: 'itemChildAdded' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]

Change-Id: I2effeb908552fa2759057cf0953ea65737be3f9a
Reviewed-by: Mitch Curtis <mitch.curtis@qt.io>