QQuickStackView: fix build
error: no matching function for call to 'QQmlComponentPrivate::initializeObjectWithInitialProperties(QV4::ScopedValue&, QQuickItem*&)'

(cherry picked from commit 6fe784b9696fc19eb8f2ba24f187d2cea4434c53)
Change-Id: Ic3db50f44912d9e5cdb71f6712fff554fc76505e
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>