QQmlJSLogger: disable warning from GCC 11 & 12
I think it's coming from the push_back in QQmlJSLogger::log(), but GCC
appears to require the warning be suppressed at the template, not the
instantiation point.

GCC 11:
qarraydataops.h:581:11: error: ‘*(QArrayDataPointer<FixSuggestion::Fix>*)((char*)&tmp + offsetof(Message, Message::fixSuggestion.std::optional<FixSuggestion>::<unnamed>.std::_Optional_base<FixSuggestion, false, false>::<unnamed>)).QArrayDataPointer<FixSuggestion::Fix>::ptr’ is used uninitialized [-Werror=uninitialized]

GCC 12:
qarraydataops.h:581:11: error: ?*(QArrayDataPointer<FixSuggestion::Fix>*)((char*)&tmp + offsetof(Message, Message::fixSuggestion.std::optional<FixSuggestion>::<unnamed>.std::_Optional_base<FixSuggestion, false, false>::<unnamed>)).QArrayDataPointer<FixSuggestion::Fix>::d? may be used uninitialized [-Werror=maybe-uninitialized]

Change-Id: I0e5f6bec596a4a78bd3bfffd16c995116afc2718
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
(cherry picked from commit 067d5a3334558c378dd67246e26cce78650e78cc)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>