Rename labs platform types to avoid duplicate type names
Qt Labs Platform and Qt Quick Dialogs contain the same type names,
which may cause issues when both modules are imported from QML.

This may be the cause of the linker error when building Qt
for Web Assembly:

wasm-ld: error: duplicate symbol: vtable for QQuickPlatformFontDialog
>>> defined in /home/qt/RTA/qt5/6.2.1/wasm_32/./qml/Qt/labs/platform/libqtlabsplatformplugin.a(mocs_compilation.cpp.o)
>>> defined in /home/qt/RTA/qt5/6.2.1/wasm_32/lib/libQt6QuickDialogs2QuickImpl.a(mocs_compilation.cpp.o)

Fixes: QTBUG-97465
Change-Id: I43dfab7cf4f56e4bfcdd4262dcf7d99f82351434
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit d0507b6d5eab28f36cc39c1f46d8a87ab76bb88e)