Initialize members to shut up gcc
Possibly a compiler bug:

In member function ‘virtual bool QmlIR::IRBuilder::visit(QQmlJS::AST::UiObjectBinding*)’:
error: ‘<anonymous>.QSpecialIntegerBitfield<QLittleEndianStorageType<unsigned int>, 0, 20>::val’
       is used uninitialized in this function [-Werror=uninitialized]
         UT i = S::fromSpecial(val);
                ~~~~~~~~~~~~~~^~~~~

This seems to be the only effective way of shutting up gcc.

Change-Id: Ib72bdcafb7336e67cf22ef67c56c7c74421eb12d
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>