QSGRhiShaderEffectNode: remove unused m_rc member
Found by Clang after includemocs:

    qsgrhishadereffectnode_p.h:145:30: error: private field 'm_rc' is not used [-Werror,-Wunused-private-field]
        QSGDefaultRenderContext *m_rc;
                                 ^

Change-Id: I915751abb01d9ff5d57c364be333ca2c171eaa97
Reviewed-by: Mårten Nordheim <marten.nordheim@qt.io>
(cherry picked from commit 8a963700499a4264edaf462d906128f662a090fc)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>