Fixed compile error in qqmlscript.cpp due to narrowing conversion.
qqmlscript.cpp:917: error: narrowing conversion of ‘6u’ from ‘size_t’
to ‘int’ inside { }

Change-Id: I2dae5b0fb8644b48bfa38bbb7bd173537a03a1a4
Reviewed-by: Matthew Vogt <matthew.vogt@nokia.com>