QQmlAdaptorModel: include qqmlglobal_p.h in header file
In other places where qqmladaptormodel_p.h is included, there are lots
of other includes which eventually result in qqmlglobal_p.h being seen.
In the new qqmldelegatecomponent.cpp, there aren't so many, so this
missing dependency became clear, at least on Windows:

  c:\users\qt\work\qt\qtdeclarative\include\qtqml\5.12.0\qtqml\private\../../../../../src/qml/qml/qqmlguard_p.h(119): error C3861: 'QQml_setParent_noEvent': identifier not found
  c:\users\qt\work\qt\qtdeclarative\include\qtqml\5.12.0\qtqml\private\../../../../../src/qml/qml/qqmlguard_p.h(113): note: while compiling class template member function 'void TestNamespace::QQmlStrongJSQObjectReference<TestNamespace::QObject>::setObject(T *,TestNamespace::QObject *)'
  c:\users\qt\work\qt\qtdeclarative\include\qtqml\5.12.0\qtqml\private\../../../../../src/qml/util/qqmladaptormodel_p.h(72): note: see reference to class template instantiation 'TestNamespace::QQmlStrongJSQObjectReference<TestNamespace::QObject>' being compiled
  c:\users\qt\work\qt\qtdeclarative\include\qtqml\5.12.0\qtqml\private\../../../../../src/qml/qml/qqmlguard_p.h(125): error C3861: 'QQml_setParent_noEvent': identifier not found

The error was because QQml_setParent_noEvent(QObject*, QObject*) was
not defined, but it is defined inline in qqmlglobal_p.h.

Change-Id: I972e2795d5a705e1170ef50b2ef7f9b124a28472
Reviewed-by: Paolo Angelelli <paolo.angelelli@qt.io>