ICC issue: cast both sides of sign-bit-changing expressions to uint
QSGNode::DirtyForceUpdate is 0x8000, so when you shift it left by 16
positions, it becomes the sign bit. Either the result of that shift
is int or sn->dirtyState is.

 qsgbatchrenderer.cpp(302): error #68: integer conversion resulted in a change of sign

Change-Id: I84e363d735b443cb9beefffd14b958f9a622348b
Reviewed-by: Tony Sarajärvi <tony.sarajarvi@qt.io>