DOM: fix use of dangling reference
Found by GCC 16:
qqmldommoduleindex.cpp:263:26: error: dangling pointer to an unnamed temporary may be used [-Werror=dangling-pointer=]
  263 |                     vNow = versionPtr->minorVersion;
      |                     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
qqmldommoduleindex.cpp:245:57: note: unnamed temporary defined here
  245 |             Version const *versionPtr = exportItem.field(Fields::version).as<Version>();
      |                                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

GCC is correct: DomItem::field returns a new DomItem by value, which
creates a new ElementT (a std::variant). It's a pointer into that object
that DomItem::as() → SimpleObjectWrapBase::as() returns.

Amends commit 52d61e705ee606f3b673c757bdf253bdf6134a3b from 6.2.

Pick-to: 6.12 6.11 6.8
Change-Id: If68159d8b150042733effffd6b6955993f3a74d7
Reviewed-by: Semih Yavuz <semih.yavuz@qt.io>