Fix build without features.settings
error: static_assert failed due to requirement 'bool(-1 == 1)'
"Required feature settings for file [snip]/qsettings.h not available."
QT_REQUIRE_CONFIG(settings);

Change-Id: I0759f884531179ed5f625f21c5559389aef5c4ad
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>