QQmlTableModelColumn: remove unused field mIndex
Found by Clang after includemocs:

  qqmltablemodelcolumn_p.h:220:9: error: private field 'mIndex' is not used [-Werror,-Wunused-private-field]
    int mIndex = -1;
        ^

Change-Id: I408d93c2f4d84d2223f971af472eabc80c31aaa3
Reviewed-by: Mårten Nordheim <marten.nordheim@qt.io>
(cherry picked from commit 910052db8aa3da1ffdced1b17609443dc1cca566)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>