masm: Repace bitwise | with || in bool expression in X86Assembler.h
Produces a warning with clang 15 on Ubuntu:

/home/ag/work/qt5/qtdeclarative/src/qml/../3rdparty/masm/assembler/X86Assembler.h:2368:23: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
            emitRexIf(byteRegRequiresRex(reg)|byteRegRequiresRex(rm), reg, 0, rm);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Similar logic already uses || so this seems to be a typo.

Change-Id: Ie539600e28748d902fbb443e47892a703003c7e6
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>
(cherry picked from commit e86019ecbddd76d6551a18595ef9dcff8560f1d4)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>