Silence a GCC 8 warning in qv4string
qtdeclarative/src/qml/jsruntime/qv4string.cpp:224:76: error: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘class QChar’ from an array of ‘short unsigned int’ [-Werror=class-memaccess]
             memcpy(ch, item->text->data(), item->text->size * sizeof(QChar));

Change-Id: Ibbb91fb017fe3cc382e4a4641f899c8ea4ef989a
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>
(cherry picked from commit 27ef77279f0cc563eac58f6ef5ea0f6ac6b570a4)
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>